#
# IA target for VitualBox
#

TARGET_ARCH=x86
TARGET_ARCH_VARIANT=x86
BUILDROID_X86_NOSSE2 := true
TARGET_CPU_SMP := true
DISABLE_DEXPREOPT := true
TARGET_COMPRESS_MODULE_SYMBOLS := false
TARGET_NO_RECOVERY := true
TARGET_HARDWARE_3D := false
BOARD_USES_GENERIC_AUDIO := false
USE_CAMERA_STUB := false
TARGET_PROVIDES_INIT_RC := true
TARGET_CPU_ABI := x86
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_BOOTIMAGE_USE_EXT2 := true
BOARD_EGL_CFG := device/androVM/vbox86/egl.cfg
ANDROVM_YV12_NOT_SUPPORTED := true
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

# For VirtualBox and likely other emulators
BOARD_INSTALLER_CMDLINE := init=/init console=tty0 vga=788 quiet
BOARD_KERNEL_CMDLINE := init=/init console=tty0 quiet androidboot.hardware=vbox86 androidboot.console=tty0
TARGET_USE_DISKINSTALLER := true

TARGET_DISK_LAYOUT_CONFIG := build/target/board/vbox_x86/disk_layout.conf
BOARD_BOOTIMAGE_MAX_SIZE := 8388608
BOARD_SYSLOADER_MAX_SIZE := 7340032
BOARD_FLASH_BLOCK_SIZE := 512
# 5000M
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5368709120
# 500M
BOARD_INSTALLERIMAGE_PARTITION_SIZE := 524288000
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
# Reserve 265M  for the system partition
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912



#Use Chrome as default HTTP
HTTP := chrome
JS_ENGINE := v8

#Wifi
BOARD_WPA_SUPPLICANT_DRIVER := WIRED
WPA_SUPPLICANT_VERSION      := VER_0_8_X
BOARD_WLAN_DEVICE           := eth1

#Bluetooth
BOARD_HAVE_BLUETOOTH := true

#OpenGL
BUILD_EMULATOR_OPENGL := true
BUILD_EMULATOR_OPENGL_DRIVER := true
USE_OPENGL_RENDERER := true
